// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	// Проверить что у пользователя есть разрешения на все устройства
	CountUserDevicesWithPermissions(ctx context.Context, arg CountUserDevicesWithPermissionsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
