version: '3.8'
services:
  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/home/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 5s
         timeout: 5s
         retries: 5
    networks:
      - backend

#  jaeger:
#    image: jaegertracing/all-in-one:1.57
#    environment:
#      - LOG_LEVEL=debug
#    ports:
#      - 14268:14268 # for serving jaeger front-end
#      - 16686:16686  # for receiving OTLP data
#    logging:
#      driver: none # intentionally turnoff the logging so it doesn't clutter the terminal

networks:
  backend:
    driver: bridge