version: '3.8'
services:
  temporal:
    image: temporalio/auto-setup:1.24.2
    environment:
      - DB=postgres12_pgx
      - DB_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7233:7233"
    networks:
      - backend

  temporal-ui:
    image: temporalio/ui:2.26.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8084,http://localhost:8090
    depends_on:
      - temporal
    ports:
      - "8088:8080"
    networks:
      - backend

networks:
  backend:
    external: false
