---
debug: true
# возможные варианты local dev prod
env: "dev"
contextTimeout: 5
log:
  level: 'debug'

jwt:
  access_ttl: 2m
  refresh_ttl: 10m
  signKey: "secret"

server:
  address: ":8080"

database:
  host: "localhost"
  port: 5432
  username: "default"
  password: "secret"
  name: "template"
  scheme: "public"
  max_pool_size: 20

greyLog:
  host: "localhost"
  port: 12201


...