version: '3'

# Глобальные переменные проекта
vars:
  DEV_TOOLS: |
    github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    mvdan.cc/gofumpt@v0.8.0
    github.com/daixiang0/gci@v0.13.6
    github.com/ogen-go/ogen/cmd/ogen@v1.14.0
    github.com/mikefarah/yq/v4@v4.45.2
    github.com/bufbuild/buf/cmd/buf@v1.53.0
    google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6
    google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.26.3
    github.com/envoyproxy/protoc-gen-validate@v1.2.1
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.26.3
    github.com/vektra/mockery/v2@v2.53.3

  DOCKER_COMPOSE_PATHS: |
    -f ./deployments/local/docker-compose.yml
#    -f ./deployments/local/docker-compose.temporal.yml
  #    -f ./deployments/local/docker-compose.jasper.yml
  #    -f ./deployments/local/docker-compose.metrics.yml

  DOCKER_COMPOSE_CMD: docker-compose  {{range $line := .DOCKER_COMPOSE_PATHS | splitLines -}}
    {{$line}}
    {{end}}

  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.3.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  SQLC: '{{.BIN_DIR}}/sqlc'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  BUF: '{{.BIN_DIR}}/buf'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-grpc-gateway'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'
  PROTOC_GEN_OPENAPIV2: '{{.BIN_DIR}}/protoc-gen-openapiv2'
  GRPCURL: '{{.BIN_DIR}}/grpcurl'
  MOCKERY: "{{.BIN_DIR}}/mockery"

  OPEN_API_WEATHER_V1_BASE: '{{.ROOT_DIR}}/shared/api/weather/v1/weather.openapi.yaml'
  OPEN_API_WEATHER_V1_BUNDLE: '{{.ROOT_DIR}}/shared/api/bundles/weather.openapi.v1.bundle.yaml'
  OPEN_API_FILES: '{{.ROOT_DIR}}/shared/api/bundles'

  MODULES: app platform shared

tasks:

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [ install ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        
        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🧼 Форматируем $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
          fi
        done
      - |
        echo "🎯 Сортируем импорты через gci ..."
        
        for module in {{.MODULES}}; do
          if [ -d "$module" ]; then
            echo "🎯 Сортируем импорты в $module"
            find $module -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/olezhek28/microservices-course-examples/)" {} +
          fi
        done


  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install ]
    vars:
      MODULES: '{{.MODULES}}'
      GOLANGCI_LINT: '{{.GOLANGCI_LINT}}'
    cmds:
      - |
        set -e
        ERR=0
        echo "🔍 Линтим все модули ..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔍 Линтим $mod module"
            {{.GOLANGCI_LINT}} run $mod/... --config=.golangci.yml || ERR=1
          fi
        done
        exit $ERR


  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ install ]
    cmds:
      - '{{.OGEN}} --target shared/pkg/openapi/app/v1 --package app_v1 --config config.yml  --clean shared/api/app/v1/app.v1.swagger.yml'
  

  deps:update:
    desc: "Обновление зависимостей в go.mod во всех модулях"
    cmds:
      - |
        echo "🔄 Обновление зависимостей в go.work"
        go work sync
        echo "🔄 Обновление зависимостей в go.mod во всех модулях"
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔄 Обновление зависимостей в $mod"
            (cd "$mod" && go mod tidy -compat=1.24) || exit 1
          fi
        done



  proto:lint:
    deps: [ install ]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: shared/proto
    cmds:
      - '{{.BUF}} lint'

  proto:gen:
    deps: [ install, proto:lint ]
    desc: Генерация Go-кода из .proto
    dir: shared/proto
    cmds:
      - '{{.BUF}} generate'

  mockery:gen:
    desc: "Генерирует моки интерфейсов с помощью mockery"
    deps: [ install ]
    cmds:
      - |
        echo '🧪 Генерация моков...'
        {{.MOCKERY}}
        

  deps:
    dotenv: ['.env']
    desc: контейнеры - запустить
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.CLI_ARGS}}"

  deps:cmd:
    dotenv: ['.env']
    desc: контейнеры - выполнить cli комнду с аргументами
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"   # пример: task deps:cmd -- exec postgres bash

  deps:status:
    dotenv: ['.env']
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} ps -a"

  deps:logs:
    dotenv: ['.env']
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} logs {{.CLI_ARGS}}"

  deps:stop:
    dotenv: ['.env']
    desc: контейнеры - остановить
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} stop"

  deps:reset-psql:
    dotenv: ['.env']
    cmds:
      - task: deps:reset
        vars:
          SERVICES: postgres

  deps:reset:
    dotenv: ['.env']
    cmds:
      - for: { var: SERVICES }
        cmd: "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.ITEM}}"
      - for: { var: SERVICES }
        cmd: "{{.DOCKER_COMPOSE_CMD}} up -d {{.ITEM}}"

  deps:app:
    dotenv: [ '.env' ]
    cmds:
      - go run app/main.go

  deps:app:migration:
    dotenv: [ '.env' ]
    cmds:
      - go run app/main.go migration up

  deps:temporal:
    dotenv: [ '.env' ]
    cmds:
      - temporal server start-dev

  install:
    desc: "Устанавливает все инструменты разработки одной командой"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - echo "📦 Устанавливаем все инструменты разработки..."
      - for: { var: DEV_TOOLS }
        cmd: GOBIN="{{.BIN_DIR}}"  go install "{{ .ITEM }}"
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s {{.GOLANGCI_LINT_VERSION}}
        }

  sql:
    - echo "SQLC"
    - "{{.SQLC}} generate file app/sqlc.yaml"
  templ:
    - echo "SQLC"
    - "templ generate ./... "