// Code generated by ogen, DO NOT EDIT.

package app_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthLoginPost implements POST /auth/login operation.
//
// Авторизация пользователя по email и паролю.
//
// POST /auth/login
func (UnimplementedHandler) AuthLoginPost(ctx context.Context, req *LoginRequest, params AuthLoginPostParams) (r *AuthToken, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthLogoutPost implements POST /auth/logout operation.
//
// Выход из системы (logout).
//
// POST /auth/logout
func (UnimplementedHandler) AuthLogoutPost(ctx context.Context, params AuthLogoutPostParams) (r *LogoutResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthMeGet implements GET /auth/me operation.
//
// Информация о текущем пользователе.
//
// GET /auth/me
func (UnimplementedHandler) AuthMeGet(ctx context.Context, params AuthMeGetParams) (r *UserMe, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthRefreshPost implements POST /auth/refresh operation.
//
// Обновление токенов с помощью refresh токена.
//
// POST /auth/refresh
func (UnimplementedHandler) AuthRefreshPost(ctx context.Context, req *RefreshRequest, params AuthRefreshPostParams) (r *AuthToken, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
