// Code generated by ogen, DO NOT EDIT.

package app_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginPostOperation  OperationName = "AuthLoginPost"
	AuthLogoutPostOperation OperationName = "AuthLogoutPost"
	AuthMeGetOperation      OperationName = "AuthMeGet"
)
