// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

package config

import "time"

// Config основная структура конфигурации
type Config struct {
	// Настройки JWT аутентификации
	JWT JWT `toml:"JWT"`
	// Подключение к PostgreSQL
	PG PG `toml:"PG"`
	// Информация о приложении
	App App `toml:"app"`
	// Переключатели функций
	Features Features `toml:"features"`
	// Уровень логирования: DEBUG, INFO, WARN, ERROR
	Log Log `toml:"log"`
	// Подключение к RabbitMQ
	Rabbit Rabbit `toml:"rabbit"`
	// Настройки HTTP/gRPC сервера
	Server Server `toml:"server"`
	// Настройки Temporal
	Temporal Temporal `toml:"temporal"`
}

// Настройки JWT аутентификации
// JWT секция конфигурации
type JWT struct {
	// Время жизни refresh токена
	RefreshTokenTtl time.Duration `toml:"refresh_token_ttl"`
	// Секретный ключ подписи токенов
	SignKey string `toml:"sign_key"`
	// Время жизни access токена
	TokenTtl time.Duration `toml:"token_ttl"`
}

// Подключение к PostgreSQL
// PG секция конфигурации
type PG struct {
	// Имя базы данных
	Db string `toml:"db"`
	// Хост базы данных
	Host string `toml:"host"`
	// Пароль БД
	Password string `toml:"password"`
	// Порт базы данных
	Port string `toml:"port"`
	// Схема БД
	Scheme string `toml:"scheme"`
	// Пользователь БД
	User string `toml:"user"`
}

// Информация о приложении
// App секция конфигурации
type App struct {
	// Название сервиса
	Name string `toml:"name"`
	// Версия приложения
	Version string `toml:"version"`
}

// Переключатели функций
// Features секция конфигурации
type Features struct {
	// Включить сбор метрик
	EnableMetrics bool `toml:"enable_metrics"`
	// Включить трейсинг
	EnableTracing bool `toml:"enable_tracing"`
}

// Уровень логирования: DEBUG, INFO, WARN, ERROR
// Log секция конфигурации
type Log struct {
	// Формат вывода: text=false , json = true
	Format bool   `toml:"format"`
	Level  string `toml:"level"`
}

// Подключение к RabbitMQ
// Rabbit секция конфигурации
type Rabbit struct {
	// AMQP URI для подключения к RabbitMQ
	AmqpUrl string `toml:"amqp_url"`
}

// Настройки HTTP/gRPC сервера
// Server секция конфигурации
type Server struct {
	// Порт debug/pprof
	DebugPort string `toml:"debug_port"`
	// Окружение: local, dev, prod
	Env string `toml:"env"`
	// Порт gRPC сервера
	GrpcPort string `toml:"grpc_port"`
	// Хост сервера
	Host string `toml:"host"`
	// Порт HTTP сервера
	HttpPort string `toml:"http_port"`
	// Основной порт приложения
	Port string `toml:"port"`
	// Порт Swagger UI
	SwaggerPort string `toml:"swagger_port"`
}

// Настройки Temporal
// Temporal секция конфигурации
type Temporal struct {
	// Хост Temporal сервера
	Host string `toml:"host"`
	// Пространство имён
	Namespace string `toml:"namespace"`
	// Порт Temporal сервера
	Port int `toml:"port"`
	// Очередь задач
	TaskQueue string `toml:"task_queue"`
}
