// Code generated by options-gen. DO NOT EDIT.
package store

import (
	fmt461e464ebed9 "fmt"

	_ "github.com/jackc/pgx/v5/stdlib"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptPgxOptionsSetter func(o *PgxOptions)

func NewPgxOptions(
	address string,
	username string,
	password string,
	database string,
	options ...OptPgxOptionsSetter,
) PgxOptions {
	o := PgxOptions{}

	// Setting defaults from field tag (if present)

	o.address = address
	o.username = username
	o.password = password
	o.database = database

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *PgxOptions) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("address", _validate_PgxOptions_address(o)))
	errs.Add(errors461e464ebed9.NewValidationError("username", _validate_PgxOptions_username(o)))
	errs.Add(errors461e464ebed9.NewValidationError("password", _validate_PgxOptions_password(o)))
	errs.Add(errors461e464ebed9.NewValidationError("database", _validate_PgxOptions_database(o)))
	return errs.AsError()
}

func _validate_PgxOptions_address(o *PgxOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.address, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `address` did not pass the test: %w", err)
	}
	return nil
}

func _validate_PgxOptions_username(o *PgxOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.username, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `username` did not pass the test: %w", err)
	}
	return nil
}

func _validate_PgxOptions_password(o *PgxOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.password, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `password` did not pass the test: %w", err)
	}
	return nil
}

func _validate_PgxOptions_database(o *PgxOptions) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.database, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `database` did not pass the test: %w", err)
	}
	return nil
}
