// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reminder/reminder.proto

package reminderv1

import (
	_ "github.com/cludden/protoc-gen-go-temporal/gen/temporal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduleReminderRequest входные данные для создания напоминания
type ScheduleReminderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный ID напоминания
	ReminderId string `protobuf:"bytes,1,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	// ID пользователя
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Заголовок напоминания
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Описание напоминания
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Время, когда нужно напомнить
	RemindAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	// Chat ID в Telegram для отправки уведомления
	TelegramChatId int64 `protobuf:"varint,6,opt,name=telegram_chat_id,json=telegramChatId,proto3" json:"telegram_chat_id,omitempty"`
	// Требуется ли подтверждение получения
	RequireConfirmation bool `protobuf:"varint,7,opt,name=require_confirmation,json=requireConfirmation,proto3" json:"require_confirmation,omitempty"`
	// Интервал повторной отправки в минутах (5, 10, 15, 30, 60)
	RepeatIntervalMinutes int32 `protobuf:"varint,8,opt,name=repeat_interval_minutes,json=repeatIntervalMinutes,proto3" json:"repeat_interval_minutes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScheduleReminderRequest) Reset() {
	*x = ScheduleReminderRequest{}
	mi := &file_reminder_reminder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleReminderRequest) ProtoMessage() {}

func (x *ScheduleReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_reminder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleReminderRequest.ProtoReflect.Descriptor instead.
func (*ScheduleReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminder_reminder_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleReminderRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

func (x *ScheduleReminderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScheduleReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduleReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduleReminderRequest) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *ScheduleReminderRequest) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

func (x *ScheduleReminderRequest) GetRequireConfirmation() bool {
	if x != nil {
		return x.RequireConfirmation
	}
	return false
}

func (x *ScheduleReminderRequest) GetRepeatIntervalMinutes() int32 {
	if x != nil {
		return x.RepeatIntervalMinutes
	}
	return 0
}

// ScheduleReminderResponse результат создания напоминания
type ScheduleReminderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID workflow в Temporal
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Текущий статус
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleReminderResponse) Reset() {
	*x = ScheduleReminderResponse{}
	mi := &file_reminder_reminder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleReminderResponse) ProtoMessage() {}

func (x *ScheduleReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_reminder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleReminderResponse.ProtoReflect.Descriptor instead.
func (*ScheduleReminderResponse) Descriptor() ([]byte, []int) {
	return file_reminder_reminder_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleReminderResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ScheduleReminderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// SendTelegramNotificationRequest входные данные для отправки уведомления
type SendTelegramNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chat ID в Telegram
	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Заголовок
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Описание
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Требуется ли подтверждение (для отображения кнопки)
	RequireConfirmation bool `protobuf:"varint,4,opt,name=require_confirmation,json=requireConfirmation,proto3" json:"require_confirmation,omitempty"`
	// ID напоминания (для callback data кнопки подтверждения)
	ReminderId    string `protobuf:"bytes,5,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTelegramNotificationRequest) Reset() {
	*x = SendTelegramNotificationRequest{}
	mi := &file_reminder_reminder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTelegramNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTelegramNotificationRequest) ProtoMessage() {}

func (x *SendTelegramNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_reminder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTelegramNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendTelegramNotificationRequest) Descriptor() ([]byte, []int) {
	return file_reminder_reminder_proto_rawDescGZIP(), []int{2}
}

func (x *SendTelegramNotificationRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendTelegramNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendTelegramNotificationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SendTelegramNotificationRequest) GetRequireConfirmation() bool {
	if x != nil {
		return x.RequireConfirmation
	}
	return false
}

func (x *SendTelegramNotificationRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

// UpdateReminderStatusRequest входные данные для обновления статуса
type UpdateReminderStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID напоминания
	ReminderId string `protobuf:"bytes,1,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	// Новый статус
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReminderStatusRequest) Reset() {
	*x = UpdateReminderStatusRequest{}
	mi := &file_reminder_reminder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReminderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderStatusRequest) ProtoMessage() {}

func (x *UpdateReminderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_reminder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateReminderStatusRequest) Descriptor() ([]byte, []int) {
	return file_reminder_reminder_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReminderStatusRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

func (x *UpdateReminderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetReminderStatusResponse текущий статус напоминания
type GetReminderStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Статус: pending, sent, cancelled
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReminderStatusResponse) Reset() {
	*x = GetReminderStatusResponse{}
	mi := &file_reminder_reminder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReminderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderStatusResponse) ProtoMessage() {}

func (x *GetReminderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminder_reminder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetReminderStatusResponse) Descriptor() ([]byte, []int) {
	return file_reminder_reminder_proto_rawDescGZIP(), []int{4}
}

func (x *GetReminderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_reminder_reminder_proto protoreflect.FileDescriptor

const file_reminder_reminder_proto_rawDesc = "" +
	"\n" +
	"\x17reminder/reminder.proto\x12\vreminder.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1atemporal/v1/temporal.proto\"\xd9\x02\n" +
	"\x17ScheduleReminderRequest\x12\x1f\n" +
	"\vreminder_id\x18\x01 \x01(\tR\n" +
	"reminderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x127\n" +
	"\tremind_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12(\n" +
	"\x10telegram_chat_id\x18\x06 \x01(\x03R\x0etelegramChatId\x121\n" +
	"\x14require_confirmation\x18\a \x01(\bR\x13requireConfirmation\x126\n" +
	"\x17repeat_interval_minutes\x18\b \x01(\x05R\x15repeatIntervalMinutes\"S\n" +
	"\x18ScheduleReminderResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc6\x01\n" +
	"\x1fSendTelegramNotificationRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x14require_confirmation\x18\x04 \x01(\bR\x13requireConfirmation\x12\x1f\n" +
	"\vreminder_id\x18\x05 \x01(\tR\n" +
	"reminderId\"V\n" +
	"\x1bUpdateReminderStatusRequest\x12\x1f\n" +
	"\vreminder_id\x18\x01 \x01(\tR\n" +
	"reminderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"3\n" +
	"\x19GetReminderStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xae\x05\n" +
	"\bReminder\x12\xc6\x01\n" +
	"\x10ScheduleReminder\x12$.reminder.v1.ScheduleReminderRequest\x1a%.reminder.v1.ScheduleReminderResponse\"e\x8a\xc4\x03a\n" +
	"\x13\n" +
	"\x11GetReminderStatus\x12\x10\n" +
	"\x0eCancelReminder\x12\x15\n" +
	"\x13AcknowledgeReminder\"\x05\b\x80\x9a\x9e\x01*\x1areminder/${! reminder_id }\x12n\n" +
	"\x18SendTelegramNotification\x12,.reminder.v1.SendTelegramNotificationRequest\x1a\x16.google.protobuf.Empty\"\f\x92\xc4\x03\b\"\x02\b\x1e2\x02 \x05\x12f\n" +
	"\x14UpdateReminderStatus\x12(.reminder.v1.UpdateReminderStatusRequest\x1a\x16.google.protobuf.Empty\"\f\x92\xc4\x03\b\"\x02\b\n" +
	"2\x02 \n" +
	"\x12F\n" +
	"\x0eCancelReminder\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x04\xa2\xc4\x03\x00\x12K\n" +
	"\x13AcknowledgeReminder\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x04\xa2\xc4\x03\x00\x12Y\n" +
	"\x11GetReminderStatus\x12\x16.google.protobuf.Empty\x1a&.reminder.v1.GetReminderStatusResponse\"\x04\x9a\xc4\x03\x00\x1a\x11\x8a\xc4\x03\r\n" +
	"\vreminder-v1B\x8e\x01\n" +
	"\x0fcom.reminder.v1B\rReminderProtoP\x01Z\x1fexample/gen/reminder;reminderv1\xa2\x02\x03RXX\xaa\x02\vReminder.V1\xca\x02\vReminder\\V1\xe2\x02\x17Reminder\\V1\\GPBMetadata\xea\x02\fReminder::V1b\x06proto3"

var (
	file_reminder_reminder_proto_rawDescOnce sync.Once
	file_reminder_reminder_proto_rawDescData []byte
)

func file_reminder_reminder_proto_rawDescGZIP() []byte {
	file_reminder_reminder_proto_rawDescOnce.Do(func() {
		file_reminder_reminder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reminder_reminder_proto_rawDesc), len(file_reminder_reminder_proto_rawDesc)))
	})
	return file_reminder_reminder_proto_rawDescData
}

var file_reminder_reminder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reminder_reminder_proto_goTypes = []any{
	(*ScheduleReminderRequest)(nil),         // 0: reminder.v1.ScheduleReminderRequest
	(*ScheduleReminderResponse)(nil),        // 1: reminder.v1.ScheduleReminderResponse
	(*SendTelegramNotificationRequest)(nil), // 2: reminder.v1.SendTelegramNotificationRequest
	(*UpdateReminderStatusRequest)(nil),     // 3: reminder.v1.UpdateReminderStatusRequest
	(*GetReminderStatusResponse)(nil),       // 4: reminder.v1.GetReminderStatusResponse
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 6: google.protobuf.Empty
}
var file_reminder_reminder_proto_depIdxs = []int32{
	5, // 0: reminder.v1.ScheduleReminderRequest.remind_at:type_name -> google.protobuf.Timestamp
	0, // 1: reminder.v1.Reminder.ScheduleReminder:input_type -> reminder.v1.ScheduleReminderRequest
	2, // 2: reminder.v1.Reminder.SendTelegramNotification:input_type -> reminder.v1.SendTelegramNotificationRequest
	3, // 3: reminder.v1.Reminder.UpdateReminderStatus:input_type -> reminder.v1.UpdateReminderStatusRequest
	6, // 4: reminder.v1.Reminder.CancelReminder:input_type -> google.protobuf.Empty
	6, // 5: reminder.v1.Reminder.AcknowledgeReminder:input_type -> google.protobuf.Empty
	6, // 6: reminder.v1.Reminder.GetReminderStatus:input_type -> google.protobuf.Empty
	1, // 7: reminder.v1.Reminder.ScheduleReminder:output_type -> reminder.v1.ScheduleReminderResponse
	6, // 8: reminder.v1.Reminder.SendTelegramNotification:output_type -> google.protobuf.Empty
	6, // 9: reminder.v1.Reminder.UpdateReminderStatus:output_type -> google.protobuf.Empty
	6, // 10: reminder.v1.Reminder.CancelReminder:output_type -> google.protobuf.Empty
	6, // 11: reminder.v1.Reminder.AcknowledgeReminder:output_type -> google.protobuf.Empty
	4, // 12: reminder.v1.Reminder.GetReminderStatus:output_type -> reminder.v1.GetReminderStatusResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reminder_reminder_proto_init() }
func file_reminder_reminder_proto_init() {
	if File_reminder_reminder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reminder_reminder_proto_rawDesc), len(file_reminder_reminder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminder_reminder_proto_goTypes,
		DependencyIndexes: file_reminder_reminder_proto_depIdxs,
		MessageInfos:      file_reminder_reminder_proto_msgTypes,
	}.Build()
	File_reminder_reminder_proto = out.File
	file_reminder_reminder_proto_goTypes = nil
	file_reminder_reminder_proto_depIdxs = nil
}
