// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

package config

import "time"

// Environment представляет окружение развертывания
type Environment string

const (
	EnvLocal      Environment = "local"
	EnvDev        Environment = "dev"
	EnvStaging    Environment = "stg"
	EnvProduction Environment = "prod"
)

// Config основная структура конфигурации
type Config struct {
	Env Environment `toml:"-"`
	JWT JWT         `toml:"JWT"`
	PG  PG          `toml:"PG"`
	// Информация о приложении
	App      App      `toml:"app"`
	Log      Log      `toml:"log"`
	Metrics  Metrics  `toml:"metrics"`
	Otel     Otel     `toml:"otel"`
	Rabbit   Rabbit   `toml:"rabbit"`
	Server   Server   `toml:"server"`
	Temporal Temporal `toml:"temporal"`
}

func (c *Config) IsProduction() bool { return c.Env == EnvProduction }
func (c *Config) IsStg() bool        { return c.Env == EnvStaging }
func (c *Config) IsLocal() bool      { return c.Env == EnvLocal }
func (c *Config) GetEnv() string     { return string(c.Env) }

//go:generate minimock -i Configurator -o ./mock/ -s _mock.go -g

// Configurator интерфейс для мокирования конфигурации в тестах
type Configurator interface {
	IsProduction() bool
	IsStg() bool
	IsLocal() bool
	GetEnv() string
}

// JWT секция конфигурации
type JWT struct {
	// Время жизни refresh токена
	RefreshTokenTtl time.Duration `toml:"refresh_token_ttl"`
	// Секретный ключ подписи токенов
	SignKey string `toml:"sign_key"`
	// Время жизни access токена
	TokenTtl time.Duration `toml:"token_ttl"`
}

// PG секция конфигурации
type PG struct {
	// Имя базы данных
	Db string `toml:"db"`
	// Хост базы данных
	Host string `toml:"host"`
	// Пароль БД
	Password string `toml:"password"`
	// Порт базы данных
	Port string `toml:"port"`
	// Схема БД
	Scheme string `toml:"scheme"`
	// Пользователь БД
	User string `toml:"user"`
}

// Информация о приложении
// App секция конфигурации
type App struct {
	// Название сервиса
	Name string `toml:"name"`
	// Версия приложения
	Version string `toml:"version"`
}

// Log секция конфигурации
type Log struct {
	// Формат вывода: text=false , json = true
	Format bool   `toml:"format"`
	Level  string `toml:"level"`
	// Включить отправку логов в Loki
	LokiEnabled bool `toml:"loki_enabled"`
	// URL Loki push API
	LokiUrl string `toml:"loki_url"`
}

// Metrics секция конфигурации
type Metrics struct {
	// Включить сбор метрик
	EnableMetrics bool `toml:"enable_metrics"`
}

// Otel секция конфигурации
type Otel struct {
	// Адрес OTEL Collector (gRPC)
	Endpoint string `toml:"endpoint"`
	// Процент трейсов для сохранения (0.0–1.0)
	SampleRate float64 `toml:"sample_rate"`
}

// Rabbit секция конфигурации
type Rabbit struct {
	// AMQP URI для подключения к RabbitMQ
	AmqpUrl string `toml:"amqp_url"`
}

// Server секция конфигурации
type Server struct {
	// Порт debug/pprof
	DebugPort string `toml:"debug_port"`
	// Окружение: local, dev, prod
	Env string `toml:"env"`
	// Порт gRPC сервера
	GrpcPort string `toml:"grpc_port"`
	// Хост сервера
	Host string `toml:"host"`
	// Порт HTTP сервера
	HttpPort string `toml:"http_port"`
	// Основной порт приложения
	Port string `toml:"port"`
	// Порт Swagger UI
	SwaggerPort string `toml:"swagger_port"`
}

// Temporal секция конфигурации
type Temporal struct {
	// Хост Temporal сервера
	Host string `toml:"host"`
	// Пространство имён
	Namespace string `toml:"namespace"`
	// Порт Temporal сервера
	Port int `toml:"port"`
	// Очередь задач
	TaskQueue string `toml:"task_queue"`
}
