// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

//go:build !production

package config

// TestFlags создает Flags с дефолтными значениями (для тестов)
func TestFlags() *Flags {
	return NewFlags(NewMemoryStore(DefaultFlagValues()))
}

// TestFlagsWith создает Flags с переопределенными значениями (для тестов)
func TestFlagsWith(overrides map[string]any) *Flags {
	vals := DefaultFlagValues()
	for k, v := range overrides {
		vals[k] = v
	}
	return NewFlags(NewMemoryStore(vals))
}
