// Code generated by configgen. DO NOT EDIT.
// Код сгенерирован configgen. НЕ РЕДАКТИРОВАТЬ.

package config

import (
	"context"
)

// FlagStore интерфейс для бэкенда feature flags
type FlagStore interface {
	GetBool(key string, def bool) bool
	GetInt(key string, def int) int
	GetFloat(key string, def float64) float64
	GetString(key string, def string) string
	// Watch вызывает onChange при изменении значения флага
	Watch(ctx context.Context, onChange func(key string)) error
	Close() error
}

// Flags предоставляет типизированный доступ к feature flags
type Flags struct {
	store FlagStore
}

// NewFlags создает Flags с указанным бэкендом
func NewFlags(store FlagStore) *Flags {
	return &Flags{store: store}
}

// BannerText — Текст баннера
func (f *Flags) BannerText() string {
	return f.store.GetString("banner_text", "Welcome!")
}

// NewCatalogUi — Включить новый UI каталога
func (f *Flags) NewCatalogUi() bool {
	return f.store.GetBool("new_catalog_ui", false)
}

// RateLimit — Лимит запросов в секунду
func (f *Flags) RateLimit() int {
	return f.store.GetInt("rate_limit", 100)
}

// ScoreThreshold — Порог релевантности
func (f *Flags) ScoreThreshold() float64 {
	return f.store.GetFloat("score_threshold", 0.75)
}

// DefaultFlagValues возвращает дефолтные значения всех флагов
func DefaultFlagValues() map[string]any {
	return map[string]any{
		"banner_text":     "Welcome!",
		"new_catalog_ui":  false,
		"rate_limit":      100,
		"score_threshold": 0.75,
	}
}
