/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Запросы на аутентификацию и работа с авторизованым пользователем
 * OpenAPI spec version: v1
 */

export interface LoginRequest {
  /** Email пользователя для входа */
  email: string;
  /**
   * Пароль пользователя
   * @minLength 6
   */
  password: string;
}
