openapi: 3.0.3
info:
  title: device
  version: v1

servers:
  - url: http://localhost:8080/api/v1
    description: Для локальной разработки
  - url: https://omv-dev.demo.megafon.ru/api/v1
    description: Development server
paths:


  /devices/electricity:
    get:
      tags:
        - Электричество
      summary: Список лектросчетчиков
      description: Устройства вкладка с электричеством
      parameters:
        - $ref: "parameters.yml#/parameters/XRequestIDHeader"

      responses:
        "200":
          description: успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
security:
  - bearerAuth: [ ]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      description: Represents error object
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
        - code
        - message
    AuthToken:
      type: object
      required: [ access, refresh ]
      properties:
        access:
          description: токен для авторизации
          type: string
        refresh:
          description: токен для получения нового access токена
          type: string

