server:
  host: localhost
  port: 8080
  env: local # prod dev local
  context_timeout: 1m
  read_header_timeout: 60s
  grace_ful_timeout: 8s

log:
  level: 'DEBUG'

PG:
  host: localhost
  port: 5432
  user: default
  password: secret
  scheme: public
  db: tracker

rabbit:
  amqp_url: amqp://guest:guest@localhost:5672

JWT:
  token_ttl: 20000m
  refresh_token_ttl: 20000m
  sign_key: secret

jasperAPI:
  host: http://localhost:80
  login: jasperadmin1
  password: bitnami
