// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"app/internal/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Users struct {
	ID        types.UserID       `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Password  string             `json:"password"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
